#需要在华为云配置项中创建的配置 除了以下还需要引入url的基础配置
data:
  #支付通知回调地址的协议,http或https
  mall.domain.protocol: ''
  #支付模块的域名+端口 如:  pay.sobeylingyun.com:32217
  mall.domain.config: ''
  #数据库mysql ip:port
  mall.mysql.url: ''
  #mysql 用户名
  mall.mysql.username: ''
  #mysql 密码
  mall.mysql.password: ''
  #rabbitmq相关
  mall.rabbit.host: ''
  mall.rabbit.port: ''
  mall.rabbit.username: ''
  mall.rabbit.password: ''
  #redis相关
  mall.redis.host: ''
  mall.redis.port: ''
  mall.redis.password: ''